"""adding rundate to model history table

Revision ID: 27cde118cb7b
Revises: 94e6978a7318
Create Date: 2025-02-05 10:58:35.382527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '27cde118cb7b'
down_revision = '94e6978a7318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_history', schema=None) as batch_op:
        # Add the 'run_date' column without a default
        batch_op.add_column(sa.Column('run_date', sa.Date(), nullable=False))

    # Now, set the default value for 'run_date' to the current date
    op.execute("ALTER TABLE model_history ALTER COLUMN run_date SET DEFAULT CURRENT_DATE;")

    # Alter the 'start_date' column to be nullable
    with op.batch_alter_table('model_history', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_history', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('run_date')

    # ### end Alembic commands ###
