"""initial migration

Revision ID: 4e05f8c8fd35
Revises: 
Create Date: 2025-02-03 11:46:44.453365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e05f8c8fd35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanatory_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_explanatory', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('joblib_loc', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('zipcode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('descr', sa.String(length=500), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('address_line', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hives_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honey_pulls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('date_reset', sa.Date(), nullable=False),
    sa.Column('date_pulled', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name=op.f('fk_honey_pulls_hive_id_hives')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('date_introduced', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name=op.f('fk_queens_hive_id_hives')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_signup_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signup_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('honey_pull_id', sa.Integer(), nullable=False),
    sa.Column('date_checked', sa.Date(), nullable=False),
    sa.Column('super_count', sa.Integer(), nullable=True),
    sa.Column('hive_body_count', sa.Integer(), nullable=True),
    sa.Column('bias', sa.Integer(), nullable=False),
    sa.Column('ants_present', sa.Boolean(), nullable=False),
    sa.Column('slugs_present', sa.Boolean(), nullable=False),
    sa.Column('hive_beetles_present', sa.Boolean(), nullable=False),
    sa.Column('wax_moths_present', sa.Boolean(), nullable=False),
    sa.Column('wasps_hornets_present', sa.Boolean(), nullable=False),
    sa.Column('mice_present', sa.Boolean(), nullable=False),
    sa.Column('robber_bees_present', sa.Boolean(), nullable=False),
    sa.Column('num_pollen_patties', sa.Integer(), nullable=False),
    sa.Column('num_sugar_syrup_frames', sa.Integer(), nullable=False),
    sa.Column('oxalic_acid_dosage', sa.Float(), nullable=False),
    sa.Column('formic_acid_dosage', sa.Float(), nullable=False),
    sa.Column('thymol_dosage', sa.Float(), nullable=False),
    sa.Column('apistan_dosage', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('weather_conditions', sa.String(length=50), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('fate', sa.String(length=50), nullable=False),
    sa.Column('has_twisted_larvae', sa.Boolean(), nullable=True),
    sa.Column('has_chalkbrood', sa.Boolean(), nullable=True),
    sa.Column('varroa_mite_count', sa.Float(), nullable=True),
    sa.Column('activity_surrounding_hive', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('stability_in_hive', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['honey_pull_id'], ['honey_pulls.id'], name=op.f('fk_inspections_honey_pull_id_honey_pulls')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspections')
    op.drop_table('signup')
    op.drop_table('queens')
    op.drop_table('honey_pulls')
    op.drop_table('hives')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('model_history')
    op.drop_table('explanatory_variables')
    # ### end Alembic commands ###
