"""adding forum models and removing queen

Revision ID: 54e5b62234a7
Revises: 5d5529c512f8
Create Date: 2025-02-06 16:00:36.443131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e5b62234a7'
down_revision = '5d5529c512f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forums_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], name=op.f('fk_messages_forum_id_forums')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_signups_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signups_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('signup')
    op.drop_table('queens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hive_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('species', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_introduced', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name='fk_queens_hive_id_hives'),
    sa.PrimaryKeyConstraint('id', name='queens_pkey')
    )
    op.create_table('signup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_signup_event_id_events'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_signup_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='signup_pkey')
    )
    op.drop_table('signups')
    op.drop_table('messages')
    op.drop_table('forums')
    # ### end Alembic commands ###
