"""removing fate column

Revision ID: 87692f145827
Revises: f08f0aeb5dac
Create Date: 2025-02-12 07:25:27.299736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87692f145827'
down_revision = 'f08f0aeb5dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('fate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fate', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
